version: '3.8'

services:
  app1:
    build:
      context: ./app1
    volumes:
      - ./app1:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - appnet

  app2:
    build:
      context: ./app2
    volumes:
      - ./app2:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - appnet

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - appnet

networks:
  appnet:

